#!/bin/bash
# This code is generated by README.org
# Go to that file run "M-x org-babel-tangle"

xcode-select --install

curl -L https://nixos.org/nix/install | sh -s -- --darwin-use-unencrypted-nix-store-volume

curl -L https://nixos.org/nix/install | sh -s -- --darwin-use-unencrypted-nix-store-volume

nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update
export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH
nix-shell '<home-manager>' -A install

cd ~
git clone https://github.com/Sauloxd/.dotfiles.git
ln -sf ~/.dotfiles/macos/home.nix ~/.config/nixpkgs/home.nix

home-manager switch
brew install

curl -sLf https://spacevim.org/install.sh | bash
