# Source for downloads
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask"

# Brew CLI bins
brew "tmuxinator"
brew "neovim"

# MacOS applications
cask "karabiner-elements"
cask "docker"
cask "amethyst"
cask "google-backup-and-sync"
cask "iterm2"
cask "visual-studio-code"
cask "steam"

