#!/bin/sh
# Two-bar layout, "true split":
#   * TOP    — all sessions as powerline tabs, on a pane-border line.
#   * BOTTOM — the normal catppuccin status bar (window tabs etc).
#
# tmux only has ONE status-position for the whole status block, so the session
# strip can't be a second status line at the top while the window bar stays at
# the bottom. Instead we render the session strip on the *pane border* at the
# top of the screen (pane-border-status top). To avoid the strip repeating in
# the middle of split layouts, it only draws on panes whose top touches the very
# top of the window (pane_top == 1 once the border row is accounted for);
# interior split borders fall through to plain separator lines.
#
# Caveat (accepted): side-by-side (vertical) splits put two top-edge panes next
# to each other, so each shows the strip across its own width. Single-pane
# windows (the common case) get one clean top bar.
#
# Invoked from tmux.conf.local *after* TPM/catppuccin load. Idempotent.

# Catppuccin Mocha palette (inline below):
#   mantle  #181825 (gutter)   surface0 #313244 (inactive bg)
#   overlay1 #7f849c (inactive fg)   mauve #cba6f7 (active bg)   crust #11111b (active fg)
# Powerline glyphs (need a Nerd Font, e.g. MesloLGS NF):  U+E0B0   U+E0B2

# Recover the catppuccin main bar. Normally it's status-format[0]; if an earlier
# run stashed it in [1] (legacy two-line layout), read that instead.
main=$(tmux show -gv 'status-format[0]')
case "$main" in
  *window-status-current-format*) : ;;
  *) main=$(tmux show -gv 'status-format[1]') ;;
esac

# --- BOTTOM: single status line = the catppuccin window bar -------------------
tmux set -g status-position bottom
tmux set -g status on
tmux set -g 'status-format[0]' "$main"

# --- TOP: session tabs on the pane border ------------------------------------
# Keep interior pane separators subtle.
tmux set -g pane-border-status top
tmux set -g pane-border-style "fg=#45475a"

# The strip honors a CUSTOM order (@sess_order) and is generated by
# session-bar-build.sh (only the top-edge pane draws it). Rebuild it whenever
# sessions are added / removed / renamed; switching sessions needs no rebuild
# because each segment highlights live & per-client via #{client_session}.
here=$(dirname "$0")
tmux set-hook -g session-created "run-shell -b 'sh $here/session-bar-build.sh'"
tmux set-hook -g session-closed  "run-shell -b 'sh $here/session-bar-build.sh'"
tmux set-hook -g session-renamed "run-shell -b 'sh $here/session-bar-build.sh'"
sh "$here/session-bar-build.sh"
