#!/bin/bash
#
#Inspired by https://github.com/mathiasbynens/dotfiles
#Sourcing files, ORDER matters.

DOTFILES_DIR=$HOME/.dotfiles

export EDITOR="nvim"

HELPERS=(
  "alias.sh"
  "paths.sh"
  "ruby.sh"
  "node.sh"
  "fzf.sh"
  "tools.sh"
)

for file in $HELPERS; do
  abs_file=$DOTFILES_DIR/terminal/helpers/$file

  [ ! -f "$abs_file" ] && echo "File '$abs_file' does not exist"

  [ -f "$abs_file" ] && source "$abs_file";
done
