#/bin/zsh

ZSH_DISABLE_COMPFIX=true
ZDOTDIR=$ZSH #zcompdump, for speed up init https://stackoverflow.com/questions/47745184/change-location-of-zcompdump-files
export ZSH=$HOME/.oh-my-zsh
export DOTFILES_DIR=$HOME/.dotfiles

# ZSH customization
plugins=(git)

# User configuration
# source $ZSH/oh-my-zsh.sh

[ -f $DOTFILES_DIR/terminal/p10k.zsh ] && source $HOME/.dotfiles/terminal/p10k.zsh

source ~/.bashrc

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
