#/bin/zsh

export ZSH=$HOME/.oh-my-zsh
export DOTFILES_DIR=$HOME/.dotfiles

# ZSH customization
ZSH_THEME="powerlevel10k/powerlevel10k"
SPACESHIP_BATTERY_SHOW="false"
COMPLETION_WAITING_DOTS="true"
ZDOTDIR=$ZSH #zcompdump, for speed up init https://stackoverflow.com/questions/47745184/change-location-of-zcompdump-files
plugins=(git)

# User configuration
source $ZSH/oh-my-zsh.sh

[ -f $DOTFILES_DIR/terminal/p10k.zsh ] && source $DOTFILES_DIR/terminal/p10k.zsh

source ~/.bashrc
